Resources:
  ClientAccountsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      "AttributeDefinitions":
        - "AttributeName": "clientId"
          "AttributeType": "S"
      "KeySchema":
        - "AttributeName": "clientId"
          "KeyType": "HASH"
      BillingMode: PAY_PER_REQUEST
      TableName: "clients"