Resources:
  InventoriesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      "AttributeDefinitions":
        - "AttributeName": "inventoryId"
          "AttributeType": "S"
      "KeySchema":
        - "AttributeName": "inventoryId"
          "KeyType": "HASH"
      BillingMode: PAY_PER_REQUEST
      TableName: "inventory"